site_name: LLM Orchestrator CLI
theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark vs light mode
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 'index.md'
  - 'Usage':
    - 'Installation': 'usage/installation.md'
    - 'Commands': 'usage/commands.md'
    - 'Chains': 'usage/chains.md'
  - 'About':
    - 'Core Concepts': 'about/core_concepts.md'
    - 'Legacy': 'about/legacy.md'
